#!groovy

pipeline {
    agent none
    options {
        buildDiscarder(logRotator(numToKeepStr: '30', daysToKeepStr: '30'))
        timestamps()
        timeout(time: 30, unit: 'MINUTES')
    }
    stages {
        stage('Test') {
            agent { node 'dev_mesos_v2' }
            steps {
                sh """
                    # Check out the latest npm-utils
                    rm -rf ./npm-utils && git clone --depth=1 git@bitbucket.org:inindca/npm-utils.git ./npm-utils
                    # Set up node with the provided version and generate a .npmrc file for our private npm repo
                    source ./npm-utils/scripts/jenkins-pre-build.sh 12.16.1 &> jenkins-pre.log
                    mv .npmrc spigot-tests/

                    npm install -g npm
                    npm install --silent

                    cd spigot-tests

                    echo "installing spigot dependencies"
                    npm install


                    echo "starting tests"
                    npm run test:ci
                """
            }
            post {
                always {
                    junit 'spigot-tests/reports/xunit-0.xml'
                    sh """
                        # Record results in TCDB
                        source ./npm-utils/scripts/jenkins-pre-build.sh 12.16.1 &> jenkins-pre.log
                        rm -rf xunit-to-tcdb
                        git clone git@bitbucket.org:inindca/xunit-to-tcdb.git
                        cd xunit-to-tcdb
                        npm install --silent
                        npm start -- -f ../spigot-tests/reports/xunit.xml -a ${ENVIRONMENT} -s
                    """
                }
            }
        }
    }
}
