name: Test Matrix
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [16, 18, 20]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and Cache Dependencies
        uses: ./.github/actions/cached-deps
      - name: Build
        run: npm run build
  test:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [16, 18, 20]
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and Cache Dependencies
        uses: ./.github/actions/cached-deps
      - name: Test
        run: npm run test
